### ISSUE TITLE
Hi,  I am building up a ROS2 Create3 bot.  I built your ros2_tts module.. How do I use it ?

### ISSUE THREAD

**Issue by jerrynsr** [andyblarblar/ros2_tts#1]
Hi,  I have ROS2 Galactic running on a RPI4 inside the payload area of my Create3.  The Create 3 works with all the irobot ROS examples.  How do I use your ros2_tts module ?     What  speach synthesizer do I need to install ? Festival ?

**Comment by andyblarblar** [comment]
Just install the pip requirements file in the node, as far as I'm aware this should install everything you need. I'm using espeak under the hood, so you may need to install that manually. The node is insanly simple right now (this was mostly a joke, to be honest). It hosts a service 'tts_speak' which takes [this message type](https://github.com/andyblarblar/ros2_tts/blob/master/tts_interfaces/srv/TtsSpeak.srv). Simply send the service that message with the words you want it to say, and it will say them. Thats really it for now, so I would encourage hacking around with it if you want, there's definitly a lot of potential, I'm just working on other projects atm. 

On another note, I don't belive the create 3 speaker just takes audio, so you'll either need to connect a speaker to the pi or hack together some sort of audio decomposer to send waveforms to their ROS2 sound service.

**Comment by jerrynsr** [comment]
Thanks for the quick reply!  I attached a usb dac/speaker to the Create 3.   I am cheating at sound output right now, recording/playing  robot moves with ros bag,  Using multiple ros bag recordings and playing a mp3 or wav sound in between with ros bag, aplay, and mpg123 all called from bash script running in a loop.  It was just a simple test  with small movements just to see if there was slop with the odometer and if I needed an optical flow sensor to track movement and write code to clean up the slop.
I'm still learning ROS.  With the irobot Create3 the RPI is connected over OTG to the RPI4.  The overall design looks like it's the same as Turtlebot 3.  You just need to add the SlamTec LIDAR and OAK D Lite camera yourself.    I didn't get the Oak D yet.  I figured I want to build a "training ui" using RVIZ.  

Am I missing a step ?  I only see the Create3 topics and actions in ROS.  

I ran the cmake, make, and install in my ROS2 environment.  Everything went well, no errors.  don't see a service tts_speak
Do I need to publish it on my RPI4 ROS node ?

ros2 service list
/e_stop
/motion_control/describe_parameters
/motion_control/get_parameter_types
/motion_control/get_parameters
/motion_control/list_parameters
/motion_control/set_parameters
/motion_control/set_parameters_atomically
/robot_power
/robot_state/change_state
/robot_state/get_available_states
/robot_state/get_available_transitions
/robot_state/get_state
/robot_state/get_transition_graph
/static_transform/change_state
/static_transform/describe_parameters
/static_transform/get_available_states
/static_transform/get_available_transitions
/static_transform/get_parameter_types
/static_transform/get_parameters
/static_transform/get_state
/static_transform/get_transition_graph
/static_transform/list_parameters
/static_transform/set_parameters
/static_transform/set_parameters_atomically
/system_monitor/change_state
/system_monitor/get_available_states
/system_monitor/get_available_transitions
/system_monitor/get_state
/system_monitor/get_transition_graph
/ui_mgr/describe_parameters
/ui_mgr/get_parameter_types
/ui_mgr/get_parameters
/ui_mgr/list_parameters
/ui_mgr/set_parameters
/ui_mgr/set_parameters_atomically

**Comment by jerrynsr** [comment]
I'm getting there.   My problem was I didn't install ros2_tts in my create3_ws profile.   After I did that and ran colcon I can see the service with ros2 see
ros2 service type /tts_speak:
tts_interfaces/srv/TtsSpeak

What is the syntax I need to use to send a message to the service ?

I am trying to send to the service using this syntax:
ros2 service call /tts_speak tts_interfaces/srv/TtsSpeak "{Hello }"

It results with an error:
the passed service type is invalid

When I verify the service type it looks fine:
ros2 service type /tts_speak 
tts_interfaces/srv/TtsSpeak

**Comment by andyblarblar** [comment]
I actually got stuck on this while writing this node, the ros2 docs don't explain this command well

What you're missing is that call argument is itself YAML, so it needs to be formatted like this:
`ros2 service call /tts_speak tts_interfaces/srv/TtsSpeak "{msg: {words: 'Im made of metal, my circuits gleam, I am perpetual, I keep the country clean'}}"`

Look at the interface and then at that string and the structure should be pretty obvious if you've used JSON before. The formatting is pretty specific though, so keep those spaces in check.

FYI you also need to have the ws sourced in the terminal where you call from, else it  will just say the interface is wrong. Ran into this issue while writing this up lol.

**Comment by jerrynsr** [comment]
That's what it was.
Here's what I have working so far on the Create3.
Joystick control for training the bot.  basically use one button on a gamepad to start ros2 bag record,  guide the robot to a target.., a round trip,  stop rosw bag record.   usb camera stream from the RPI4 to my linux desktop through ssh -X.    
Later on I plan on using the ros2 bag playback.  When a Blink camera triggers and IFTTT event the Create3 bot will go to the closest room to the outdoor camera and bark like a dog.   That's the first test.  I'm saving up for an Oak D Lite now.
Thanks a lot for ros2_tts,
